feat: implement disconnect
1natsu172/bluevery pull request #59
Opened 2021-07-08 15:53 UTC by ytka

# Issue
#55

2021-07-08 15:55 UTC, ytka commented on src/interface.ts
> +  disconnect: ToBetterOptions & {};
@1natsu172 
disconnect()ですが、切断の場合も omoiyariTimeを入れたほうがよいでしょうか？
また、ToBetterOptions を WithMustTimeoutにするかどうかは、実際の動作結果次第でしょうか。

2021-07-29 09:09 UTC, 1natsu172 commented on src/interface.ts
> +  disconnect: ToBetterOptions & {};
@ytka すみませんWIPなのでコメント気づいてませんでした。

omoiyariはいらないんじゃないかなーと思います,disconnectしたあとにbleの処理しない(できない)と思うので。

mustTimeoutにするかはおっしゃるように実際の動作次第ですね。たとえばdisconnect呼んだタイミングで、peripheral側がすでにdisconnect処理に入っていて、promiseがpendingのまま返ってこないとかがあり得そうです(想像なので実際に起こるかは不明),

2021-07-30 14:10 UTC, ytka commented on src/interface.ts
> +  disconnect: ToBetterOptions & {};
> omoiyariはいらないんじゃないかなーと思います,disconnectしたあとにbleの処理しない(できない)と思うので。
> 
> mustTimeoutにするかはおっしゃるように実際の動作次第ですね。たとえばdisconnect呼んだタイミングで、peripheral側がすでにdisconnect処理に入っていて、promiseがpendingのまま返ってこないとかがあり得そうです(想像なので実際に起こるかは不明),

わかりにくかったですね。回答ありがとうございます。
なるほど。それならまずはomoiyariもmisrTimeoutもないシンプルな実装から始めるでも良さそうですね。
やっていきます。

2021-08-08 13:21 UTC, ytka commented
@1natsu172 

disconnectの実装を修正し、サンプルコードに disconnectを呼び出す実装を追加しました。
AND UC352BLEのサンプル実装では、ペアリング時に必要な読み書きが終わったらすぐに disconnectを送るようにしています。その結果、ペアリング時にタイムアウトを待たず、デバイスとの通信が即終了できるようになりました。

あとはユニットテストを通したいのですが、`blueveryCore.test.ts` に disconnectのテストを追加したところ、以下のエラーになりました。(テストコードは connectのテストを参照しました)
apply でのエラーなので、disconnectを toBetterPromiseでラップするあたりが関係するのかもと思ったのですが、何かわかりますでしょうか。

```
  ● BlueveryCore › disconect › disconnect: should be change disconnect of state the managing peripheral

    TypeError: Cannot read property 'apply' of undefined

      10 |       return await pFn(...fnParams);
      11 |     } catch (error) {
    > 12 |       throw new Error(error);
         |             ^
      13 |     }
      14 |   };
      15 | }
```

2021-08-08 19:18 UTC, 1natsu172 commented
@ytka 修正してテスト動くようにしました。 ble-managerのメソッドはnative module関わってくるのでmockしないと該当のエラーになります。

ちなみにテスト自体は動くようにしただけでfailする状態です（未完の状態でテストが動かなくて困ってしまったのかと察して余計なコミットは避けました）

PRコメントで1点実装のchange request送りますので、そちら実装対応してもらえればと思います（他の実装コピペでOKなはずです）

P.S. ついでに toBetterPromiseの用法のミスを見かけたので直しました。こちらもコミットを見てもらえれば 🙏

2021-08-08 19:23 UTC, 1natsu172 requested changes
よろしくお願いします 🌵

2021-08-08 19:23 UTC, 1natsu172 commented on src/blueveryCore.ts
> +
L355でやってるような
```
const isPassedRequireCheck = await this.requireCheckBeforeBleProcess();
    debugBlueveryCore('connect: isPassedRequireCheck', isPassedRequireCheck);
    if (isPassedRequireCheck === false) {
      return false;
    }
```

の処理を挟んで欲しいです。
BLE処理する場合は事前にこのメソッドでinitializeやpermissionチェックします。（デコレーターで実装するかすごく悩んだんですが、色々があってデコレーター実装しない方針にしてます）

2021-08-09 13:11 UTC, ytka commented
@1natsu172 
修正や追加などありがとうございます。
Permissionの追加と disconnectテストの修正および、ラインカバレッジをカバーできるようなテストを追加しました。
PRRお願いします 🙏

2021-08-09 15:24 UTC, 1natsu172 approved these changes
![LGTM](https://image.lgtmoon.dev/136559)

よさそうです！ありがとうございます！

2021-08-09 15:25 UTC, 1natsu172 commented
@ytka mergeします！

2021-08-09 15:25 UTC, merged